### ISSUE TITLE
Review and improve core collection libraries

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#103]
Bosque does not provide loops and we want to minimze the use of recursion so having a rich and expressive core collection library is critical. The current library in [collections.bsq](https://github.com/Microsoft/BosqueLanguage/blob/master/ref_impl/src/core/collections.bsq) is a start but needs improvement. This is a meta issue is to track missing API's and container types.

Action items:
* Review LINQ, lodash, STL, etc. to see what operations they expose that we may want to include as well.
* Review some loops in C++/C#/Java code to ensure we can reasonably express most of them.
* Review some ML/Haskell/OCaml code to see if there are any features we should adopt from there as well.

**Comment by mrkmarron** [comment]
Issue #93 brings up subsampling in an array. We are missing `mapWithIndex`, `filterWithIndex`, etc. style operations. Should we add these as separate APIs or update the existing map to have an optional index operation for the `List` concept?

**Comment by illeatmyhat** [comment]
I'll attempt to advocate for the second case. Do you mean that `map` would be overloaded for the List concept to have an optional index parameter, and if so would functions be forced to acknowledge the existence of optional parameters?
i.e. `abstract method map[V](f: Transform[[T, U?], V]): List[V];`
This is a complex question--I have never been a fan of Javascript's handling of optional parameters simply because the lack of static typing made it difficult to figure out exactly what a function's prototype is, but it shouldn't be an issue for this language as the information is all there.

That being the case, it may prove annoying for programmers to always have to acknowledge the parameter `U?`, as analysis tools may bug them about unused variables.
If we were to allow functions to define less parameters than they actually receive (thereby not acknowledging the existence of `U?`), this could lead to a problem where optional parameters must be defined after required parameters, but at the same time could be resolved by calling using named parameters.

**Comment by illeatmyhat** [comment]
So the List concept would have its own `map` function with a slightly different prototype?
i.e. `abstract method map[V](f: Transform[[T, U?], V]): List[V];`
I do have a preference for less verbose function names, but at the same time this would splinter the API and you'd have multiple different ways to `map` over a List, which may confuse people.
You could have people zip a list with its indices.

A more controversial approach would be to give the regular map function an optional index, and in the JavaScript style, people would define lambda expressions that don't include the extra parameters when they don't need it. Such a choice would have far-reaching implications though, such as being able to pass extra parameters to functions without knowing that it doesn't work, the position of optionals in the parameter list (Python), what analysis tools should do with unused parameters (to squiggle or don't)...

**Comment by illeatmyhat** [comment]
Instead of this, you could have people zip a list with its indices, which brings up questions about a convenience API for infinite generators.

But to actually answer the question, an option would be to change `List.map()` to have an optional index parameter?
i.e. `abstract method map[V](f: Transform[[T, U?], V]): List[V];`
I do have a preference for less verbose function names.
But then we have to consider what analysis tools should do with unused optional args, because  I think that optional types are not the same thing as optional parameters.
As I understood the syntax from the paper, parameters missing from a function call are automatically set to `none` (for entity constructors), so it's not as if optional parameters don't exist, so to support the use case of an optional index parameter, maybe there should be a more explicit syntax for optional parameters?

**Comment by mrkmarron** [comment]
I could also see giving `map` a signature that takes a simple _or_ indexed function:
```
method map[V](f: fn(_: T) -> V | fn(_: T, _: Int) -> V): List[V];
```
This is a bit ugly but once you have seen it 1-2 times it is a simple pattern to understand (and we can use it in other similar cases in the stdlibs). It does complicate lambda inference a bit as well though.

**Comment by illeatmyhat** [comment]
Does this mean that implementations will have to pass a certain set of arguments based on what the type of the function is determined to be?
If so, then this approach may have less utility for users than simple overloading and dynamic dispatch.
