### ISSUE TITLE
Why Collections concept has max min and sum abstract methods?

### ISSUE THREAD

**Issue by joelibaceta** [microsoft/BosqueLanguage#134]
Reading the `collections.bsq` implementation, I found `min` `max` and `sum` abstract methods  in the `Collection` concept, but aren't we assuming here that  the collection contains numeric values? perhaps this functionality could be solved by implementing a `reduce(p: Predicate[T])` method or a `.map` iteration ?.

**Comment by mrkmarron** [comment]
The motivation is a little subtle and tied to future goals in the language. For doing formal symbolic analysis it is possible to write precise formula that describe the behavior of min/max/sum/count. However, it is **not** possible to do this for a method like `reduce` or `fold`. In fact analyzing these operators is basically as hard as dealing with loops.

So, our ideal library should include all the common things you would otherwise use a `reduce` for. As you notice these require the type of the list `T` to be `Int` which is enforced by the `{when T Int}` notation so that these methods are only instantiated for `List[Int]` but not other list types.

**Comment by mrkmarron** [comment]
Closing and moving discussion to #103.
