### ISSUE TITLE
A Math library could be useful as a core math.bsq implementation ?

### ISSUE THREAD

**Issue by joelibaceta** [microsoft/BosqueLanguage#136]
Bosque provides a nice approach for lambdas, recursion or data operations, a simple Math implementation, could make building functional mathematical algorithms easier.

Do you think this implementation could be useful?

Math methods proposed:
`acos` `acosh` `asin` `asinh` `atan` `atan` `cos` `sin` `exp` `sqrt` `log` `tan` `tanh`  `mod`

**Comment by mrkmarron** [comment]
Yes, there are some great opportunties here. I have intentionally not included floating point operations in the core library yet since people often use them inappropriately (e.g., for calculating amounts of money) and there are many subtle things about how they work (instability etc.). 

It would be great to explore this a bit both with a nice set of library functions _and_ things like a specialized `Float::sum(...args: List[Float]): Float` that will do the sum intelligently to avoid lost precision or take advantage of specialized hardware.

**Comment by joelibaceta** [comment]
I got it, it is nice approach, maybe something like the Kahan summation algorithm.

**Comment by jakalkhalili** [comment]
#139 Added some of it

**Comment by mrkmarron** [comment]
Merging with issue #103
