### ISSUE TITLE
What's docent about method and function? 

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/BosqueLanguage#142]
I can't understand why there are method and function. What are differences between them?

**Comment by jakalkhalili** [comment]
Methods are used in entity, functions aren't.

**Comment by orcmid** [comment]
I know you closed this with that response.  I wanted to point out a subtlety that goes way back.

Technically, since &function_name provides a reference to a function (and should work with lexical binding), one might also expect &obj_instance.method to provide something similar, although it may require construction of a closure in an execution model (such as C++) that requires the "this" to be provided by the caller, even if hidden by sugar.

I had a conversation with Bjarn Stroustrup about this when C++ was new to the public.  There were a couple of difficulties.  One was about execution overhead, although I remain skeptical.  The other was about how the C++ work was required to effectively compile down to C.  So constructing closures, and dealing with their locality in a lexical environment was not in the cards.  It still might not be.  

The third case, which didn't come up as I recall, has to do with assigning pointers out of scope.  So the pointer mechanism is not a great choice, with returning an object a far better notion, operationally.  All of the lifecycle management seems to work better there.

Assuming Bosque is more on the side of the functional-programming angels, one might want to revisit some of this.

**Comment by khoshroomahdi** [comment]
@orcmid thanks
