### ISSUE TITLE
The type position 

### ISSUE THREAD

**Issue by jamalroger** [microsoft/BosqueLanguage#163]
Hi, developers 
Thanks for developing this new language. 
The position type of the variables it's not good for developing 
It's very difficult to programming with this role. 
I suggest to make it like
 Int:v1, v2, v3
Because the first thing tha't the programmers think is the type thanks. ☺☺

**Comment by wandyezj** [comment]
The order is dependent on the language, Bosque follows the order in TypeScript for example.


Additionally, it can be convenient for the type to be automatically determined based on the return type of the assignment.

TypeScript

```TypeScript
// The type of s can be inferred by assignment.
const s = "string";
```
C#

```csharp
// the type of s can be inferred by assignment
var s = "string"

// if the type is complicated this can be especially convenient
var complex = FunctionWithComplexReturnType()
```

There is similar functionality in C++11 with auto.


I've personally found that declaring multiple variables per line tends to be more difficult to read than a single variable per line that is assigned a value. Especially when it is required that the variable be assigned a value.

In some languages it is critical that variables be assigned values at initialization otherwise they can be assigned garbage values which can lead to inconsistent behavior and make it incredibly difficult to debug them later.

**Comment by mrkmarron** [comment]
Cleaning up as the discussion seems to have stopped.
