### ISSUE TITLE
'var' doesn't seem to meet the Bosque design goals

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/BosqueLanguage#164]
I'm confused: after reading https://github.com/microsoft/BosqueLanguage/blob/master/docs/language/overview.md#5.3-Variable-and-Scoped-Access, which mentions:

> All values in the Bosque language are immutable!

and

> updatable variables 

1. Aren't variables inherently updatable, being variables? If the intention was for them not to be updated, they'd be constants, not variables. 

2. If variables exist, how can they be immutable?

3. I keep seeing examples like:

```
var a = np(1, 2);   
```
If `a` isn't intended to be changed, and Bosque is attempting to eliminate unnecessary complexity, why isn't this just:

```
a = np(1, 2)
```

**Comment by orcmid** [comment]
I think this is a hold-over from other languages who employ **var** for mutable entities.  It might be more appropriate to say

  `**val** a = np(1, 3)`

as  a statement form.  

There may also be some confusion about binding of a defined "variable" for its free occurrences in subsequent references in the scope of the definition.

I notice **val** feels awkward, but just `a = np(1, 3)` creates much confusion with assignment rather than definition/declaration.

I am also puzzled about the immutability issue.

**Comment by mikemaccana** [comment]
How does immutability affect declared variables with no value? Are declared variables with no value even possible?

**Comment by orcmid** [comment]
> How does immutability affect declared variables with no value? Are declared variables with no value even possible?

Another good reason to dump **var**.

**Comment by catchmareck** [comment]
> How does immutability affect declared variables with no value? Are declared variables with no value even possible?

No, it is not. It would not make sense to allow that. If you try to declare an immutable variable with no value assigned then the following error will be thrown:

```
Parse error -- Const variable declaration must include an assignment to the variable on line [...]
```

So as you can see declaring an immutable variable with no value is forbidden on the parsing level.

**Comment by mikemaccana** [comment]
OK then since 'variables' must have values, it sounds like assignment should be possible without using `var` or anything similar. 

The most minimal syntax to achieve that would be `foo = 'bar'`. `let foo = 'bar'` would work too. 

Not using equals improperly (like most programming languages do), you could also maybe do `foo: 'bar'`. 

`var` is misleading for an immutable value, and `val` is nice but our finger memory is going to accidentally turn it into `var` a lot.

**Comment by orcmid** [comment]
> The most minimal syntax to achieve that would be foo = 'bar'. let foo = 'bar' would work too.
> Not using equals improperly (like most programming languages do), you could also maybe do foo: 'bar'.
> var is misleading for an immutable value, and val is nice but our finger memory is going to accidentally turn it into var a lot.

1. I think the undecorated "=" for assignment has been lost to us, especially since assignment is allowed in Bosque (i.e., foo was previously declared var!).  And there will be finger memory issues again.

2. Concur about **var** versus **val** and finger memory.  I have trouble with brain memory -- I still think **var** even though I know it is not quite right, especially when writing as functionally as one desires.  Although I have no problem with **val** when writing SML.  Odd.  Still agree a language should not have both.

3. I wonder if these are powerful enough, although take a little bit more on getting lexical scoping done properly.

> **let** _def-form_[, _def-form_]...; [_statement-sequence_]       (* a statement-sequence *)

> **let** _def-form_[, _def-form_]... **in** [_balanced-expression_]            (* a balanced expression *)

> _undangled-expression_ **where** [_def-form_[, _def-form_]...   (* avoiding **else** scope ambiguity *)

Scoping mutual recursions takes more thought.

**Comment by wandyezj** [comment]
Since assigned values are immutable, would it make sense to take an idea from TypeScript and use const?

It's nice that const in Bosque for objects is much stricter than TypeScript. ;)

```TypeScript
const foo = "bar";
```

**Comment by wanton7** [comment]
I have always hated misleading `const` keyword in JavaScript. Constant would mean it's value never changes during application lifetime. I also think `var` keyword is just fine for immutable variables because they are still variables even if they are immutable ones.

I think OP is mixing up immutability and reassigment and I think documentation is misleading in that regard. Reassigning variable doesn't mean variable cant't be immutable. I think docs should be changed so that mutable word is changed to reassignable.
