### ISSUE TITLE
REPL for Bosque

### ISSUE THREAD

**Issue by davidh38** [microsoft/BosqueLanguage#227]
I would like to use a REPL in Bosque like i can use it in clojure, python etc. Is there something alike in this project?

**Comment by mrkmarron** [comment]
Hi, we don't have a repl at this point in time. We took the REPL use scenario into consideration during the language design and made sure that we didn't make it difficult/impractical to support later. However, for the initial phase where we were iterating on various designs the implementation of a REPL wasn't a priority.

Can you provide some more info on how a REPL would fit in your workflow and what kinds of problems you are working on?

Thanks

**Comment by davidh38** [comment]
Hello mrkmarron,

using a REPL is a much more convenient way of programming. Getting instant feedback from the REPL is just a good way of exploring a language, new libraries or of writing normal production code. For example, after having worked on a function in the REPL, you can put it in your source code and be quite sure that it works in isolation. REPLs are mostly easy accessible from IDEs or are even builtin.

I just had a look at your paper and found the ideas interesting, so i started to write some code and after some examples, i quickly came to the conclusion, i am missing a REPL.

**Comment by alejandrosocorro** [comment]
Hi, as davidh38 said in the previous comment, having a REPL has many benefits, one of them is providing a way to explore the language, serving as a way to interact with the code you're developing or to explore and use new libraries.

Most mainstream programming languages have them, one example being Python, which besides it's own REPL, the [IPython](https://ipython.org/) package was a great one that eventually spin off and gave birth to the [Jupyter](https://jupyter.org/) project, which provides interactive programming for many other languages.

Overall I'm strong believer than a great on-boarding experience and easy ways to explore the language and its ecosystem is almost mandatory these days and at the same time can greatly boost adoption.

**Comment by beem812** [comment]
I think probably the other two posters have given good enough explanation, but in addition to what they've said, working in a clojure editor with a repl plugin means that in the same file that I am currently developing in, I can evaluate any chunk of code within that file by sending that top level code block out to the repl. The result of that is that I can see the output of a function displayed just after that chunk of code: 

![top-level-comment-eval](https://user-images.githubusercontent.com/46542509/82373565-bcac6380-99eb-11ea-89d7-d27e9b2ae3a2.gif)


The white arrows are pointing to the result of sending the evaluated code to the repl. As a result of this style of development on say a rest api, the application is left running, the code you want to test is put in to that top level `(comment ...)` function which keeps the code inside from being pulled in to the running app, and you can test out what you want in there then move it out of the comment function when you're ready for the code to be hot loaded in to the running app. The only reason the amazing tooling in clojure isn't talked about more is because it's attached to such an "interesting" language. It'd be amazing to have something similar in a more familiar language especially one with static typing.
