### ISSUE TITLE
It would be nice to use Bosque from another language

### ISSUE THREAD

**Issue by nono** [microsoft/BosqueLanguage#237]
In the current state, Bosque is too young and limited to write a full program in it (the lack of IO in particular). But, I think it could be really nice to use Bosque for writing libraries for other languages. In particular when a subproblem can be extracted as a set of pure functions (cryptography, graphs algorithm, mathematical things, etc.), it would be nice to have this subproblem in Bosque and let the other language does the glue around it (GUI, files reading and writing, network stuff).

Is it possible to transpile Bosque to JS or TS? Or to compile it to .dll/.so and use it from a compiled language?

**Comment by mrkmarron** [comment]
I definitely agree with this summary. 

Currently we support compilation to C++ that can then be compiled/linked as needed. One option is to generate a N-API native module to allow Bosque use from Node.js.

We are also working with the [Morphir ](https://github.com/Morgan-Stanley/morphir)project on the possibility of transpiling so that Bosque can be used in their platform.

It would be nice to transpile to TS/JS as well but we don't want to overload on the number of translation systems we need to maintain/keep in sync.
