### ISSUE TITLE
Type Names to Use Full Words

### ISSUE THREAD

**Issue by iddan** [microsoft/BosqueLanguage#238]
**What feature do you think could be better?**
Type names were using full words.

**Why do you think the current design is unsatisfactory? Please provide a code example if possible.**
`Bool` is short for "boolean". In JavaScript, it is called `Boolean`. Don't see why it should be different.

**Do you have a proposed alternative design?**
Full names for all types.

**Comment by Honga1** [comment]
It's a good question to ask. Especially since we see two different representation of bool in javascript - making things somewhat confusing. ie:

```js
true instanceof Boolean === false
typeof true === "boolean"
```

For other prior art to consider: 
- [Rust - "bool"](https://doc.rust-lang.org/std/primitive.bool.html)
- [OCaml - "Bool"](https://ocaml.org/api/Bool.html)
- [C# - "bool"](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/bool)

So the question is for consistency with existing semantics, or consistency with a new ideology. Personally I favor `Boolean` but it's probably not worth changing just for this case.
