### ISSUE TITLE
Implement rec keyword and support

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#27]
Implement the `rec` keyword and support. I would like to do CPS conversion so we always have a bounded stack.

**Comment by clegoz** [comment]
I've implemented some of it. Currently supports only namespace functions. I don't think is ready but it should be enough for testing/education. You could clone it from [here](https://github.com/clegoz/BosqueLanguage/tree/tail-call). ([commit](https://github.com/clegoz/BosqueLanguage/commit/ce8ab73236f9cb784fa584dda0ee739753bc24f7))

Example:
```
namespace NSMain;

function incrementRecursive(n: Int, max: Int): Int {
    _debug(n);
    return n < max ? rec incrementRecursive(n + 1, max): n;
}

entrypoint function main(): Bool {
    var test = incrementRecursive(1, 99999999);
    return true;
}
```

**Comment by orcmid** [comment]
I'm surprised to see rec, if needed at all, on the reference rather than the declaration.

Although function rec f( ... ) ... was a common idea, it seems that practice involves function recursiveness being the default with regard to static name resolution within lexical structure.  That seems to be the approach with SML, and it tends to be more natural.  It does require some trickery when the inner call is intended to be to an outer declaration, not the current one.

The additional case of mutual recursion has to be handled a different way.

There also needs to be something else for anonymous function definitions.  

I should zip my lip until I look more closely at the Bosque definition material.
