### ISSUE TITLE
Variable threading

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#34]
Often we need to thread an "environment" through code:
```
var env = ...;
@[var res1, env] = foo(env);
@[var res2, env] = bar(env, res1);
...
```
This is clumsy and verbose. We would like to thread env as a updateable ref parameter instead:
```
var env = ...;
var res1 = foo(ref env);
var res2 = bar(ref env, res1);
...
```
Where foo and bar can use/modify the env parameter.

**Comment by mrkmarron** [comment]
Let me try a more detailed example to (hopefully) clarify.

```
function inc(ref i: Int): Int {
    var res = i;
    i = i + 1; //rebind the argument variable value

    return res;
}

var! ctr = 0;
var val = inc(ref ctr);

//ctr == 1
//val == 0
```

**Comment by lochbrunner** [comment]
I see, but in section 0.1 you state that

> From this perspective the natural choice for the Bosque language is to adopt a pure functional model with immutable data only.

Therefore I would recommend the pure function approach `@[var res1, env] = foo(env);` instead of mutable references which may lead to (hidden) side effects, if this is not necessary.

It might also be a question of the purpose of that language: Does it target near-hardware software development or high-level software development like web-development?

PS. See my first interpretation of this question as a inspiration :D

**Comment by wanton7** [comment]
What if you have another function that also takes in `ref i: Int` and you call it inside `inc` function, can you also give same `i` to it as ref parameter? If it possible then you might have to hunt code that updates `env` from deep call tree. What happens if async or multithreading is added and that ref can escape to some concurrent code that updates it? I think this feature will make code much harder read, to reason about and will be source of lot of bugs.

**Comment by wanton7** [comment]
Maybe more complex pipe operator would be a solution, that could pipe multiple variables instead of one?
