### ISSUE TITLE
Map<K, V>::add is missing

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#342]
**Describe the bug**

Trying to compile this example: 

```js
namespace NSMain;

entrypoint function main(): Map<Int, String> {
    var m = Map<Int, String>@{1 => "a", 2 => "b"};
    return m.add(3, "c");
}
```

...produces this error:

`Parse error -- [".\\test.bsq",5,"Method not defined for type 'NSCore::Map<NSCore::Int, NSCore::String>'"]`

Obviously, Map's **add** method is missing.

First, I have tried to hook it up as the needed functionality seemed to be already available. I found `s_add` and `s_unsafe_add` in **core/cpp/map.bsq**. Also `map_unsafe_add` in **stmtbody_emitter.ts**.

However, my trial&error change in **core/cpp/map.bsq**

```js
method add(k: K, v: V): Map<K, V> {
     return Map<K, V>::s_add(this, k, v);
}
```

...produced a new error:

`Parse error -- ["C:\\Projects\\BosqueLanguage\\impl\\bin\\core\\cpp\\map.bsq",107,"Constant value not defined for type 'NSCore::Map<NSCore::Int, NSCore::String>'"]`.

I am not sure what the error really means and doing further experiments could only lead to even more obscure errors, so it's better to stop here and open a new issue.

**Comment by brakmic** [comment]
Well, the one weird "constant value" error has to do with a missing entry for `s_add` in **map.bsd**. After I have added this:

```js
hidden static s_add(m: Map<K, V>, k: K, v: V): Map<K, V> #map_unsafe_add
```

...it disappeared and the standard error for non-implemented methods appeared:

`Error -- AssertionError [ERR_ASSERTION]: Need to implement -- NSCore::Map::s_add`.

Looks like it could be possible to inject a single line of C++ code that internally calls **std::map::insert**?

**Comment by mrkmarron** [comment]
The challenge is that the operations on Map<K, V> need to be functional. This is expensive to support and, in theory for Bosque you should not be adding individual items to a map frequently, instead you should use bulk operations to do the transforms instead of iterative single item operations.

So, the API for map specifically excludes single item `insert` and `remove`. This let's us implement the map as a very efficient sorted array -- which is usually a great option. In the case where you really need to iteratively insert/remove from a Map, like say a fixpoint calculation, we want to have a `DynamicMap` (defined but not implemented) which will use [RBB-trees](https://dl.acm.org/doi/pdf/10.1145/3110260) to support reasonably efficient dynamic add/remove on maps and sets. However, implementation of these structures is non-trivial.

**Comment by brakmic** [comment]
Then I should rather be using methods like`merge`, `mergeall`, `union` etc.?

The reason I started searching for `add` was that it was the last unimplemented thing in `morphir-bosque` code. Their code is fairly "old" as Bosque change quite a bit. :)

So I thought, through updating their code I could also learn a few new things.

**Comment by brakmic** [comment]
Well, I now have an implementation of `add`, but I don't know if it would make any sense to open a PR?

This is how the compilation looks like. 

```shell
PS C:\Projects\BosqueLanguage\demos> exegen.cmd .\test.bsq -o test
Compiling Bosque sources in files:
.\test.bsq
...
Transpiling Bosque assembly to C++ with entrypoint of NSMain::main...
Writting C++ files...
Compiling C++ code with clang.exe  -g -DBDEBUG -std=c++17 into exe file "test.exe"...
Done with executable -- test.exe
PS C:\Projects\BosqueLanguage\demos> .\test.exe
{1 => "a", 2 => "b", 3 => "c"}
```

Have also added a test for `addop` and registered it in `test.json`.
