### ISSUE TITLE
Map<K,V> can't be instantiated when V=concept and members V=entity

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#346]
**Describe the bug**
I can't compile a Map<K,V> whose V type is a concept when potential members are entities that provide the very concept.

An example of failing code could look like this:

```js
namespace NSMain;

concept Car {
}

entity Tesla provides Car {
    field id: Int;
    field model: String;
}

entrypoint function main(): Map<Int, Car> {
    let tesla3 = Tesla@{id=1, model="3"};
    let teslaS = Tesla@{id=2, model="S"};
    let cars = Map<Int, Car>@{1=>tesla3, 2=>teslaS};
    return cars;
}
```

I am not sure if this behavior is expected or simply a missing feature.

**Comment by mrkmarron** [comment]
Templates are univariate and, as a result, `List<Tesla>` is not a subtype of `List<Car>`.

In this example the shorthand notation `1=>tesla3` is equivalent to the code `MapEntry<Int, Tesla>{1, tesla3}` which is not type compatible with the expected type `MapEntry<Int, Car>` to construct the map. 

This is slightly obnoxious. If you look at the MapEntry definition you will see it is marked as `convertable` and has an explicit conversion operator `convert<T, U>` which we want the compiler to auto insert so that we don't need to manually muck with this all the time  (`see also Result<T, E>`).

Anyway the following code compiles and runs as expected.

```
entrypoint function main(): Map<Int, Car> {
    let tesla3 = Tesla@{id=1, model="3"};
    let teslaS = Tesla@{id=2, model="S"};
    let cars = Map<Int, Car>@{1=>tesla3.as<Car>(), (2=>teslaS).convert<Int, Car>()};
    return cars;
}
```

**Comment by brakmic** [comment]
Many thanks for the clarification. :)
