### ISSUE TITLE
Question: Threading / Async

### ISSUE THREAD

**Issue by Andersmholmgren** [microsoft/BosqueLanguage#68]
What is the thinking around threading model? Will it adopt a `async / await` model, `coroutines` or something else?

**Comment by mrkmarron** [comment]
This will be left up to the host runtime (like JavaScript does not provide its own event loop or IO facilities). For the host I am very interested in some of the state-machine designs (the [P langauge](https://github.com/p-org/P)) but this is an open issue for experimentation.

**Comment by Andersmholmgren** [comment]
ES 8 has [`async / await` as keywords](https://www.ecma-international.org/ecma-262/8.0/#sec-async-function-definitions) though right?

Do you foresee no need for any language level support in Bosque?

**Comment by mrkmarron** [comment]
There are the async/await keywords but (to the best of my knowledge) the implementations use the host provided microtask queues.

As part of research mindset in this project I would like to see how far we can go without adding any lanugage support for environmental interaction but this is definitely an open question.

**Comment by Andersmholmgren** [comment]
Given how pervasive IO is in modern development (web, cloud ...) I do think it is worth considering how it will fit. From experience dealing with Promises etc is a potential area of bugs & flakiness.

FWIW, I must admit when I first saw the pipeline syntax my first thought was that it was for asynchronous streams till I read it a second time.

**Comment by wanton7** [comment]
@Andersmholmgren there is always green threads instead of async await keywords & similar. Google's Go language runtime as example uses green threading. Project Loom for Java that tries to implement green threading for JVM.
I'm C# developer by profession but I find Go's green threads much cleaner and simpler from programmers perspective compared to poluting your code with async and await keywords.

There is also Erlang's VM called BEAM that uses actor model and preemptive multitasking for building highly concurrent systems where every actor runs in separate lightweight "process" handled by BEAM.

**Comment by wanton7** [comment]
Maybe of interest. Golang is switching to non-cooperative preemption https://github.com/golang/go/issues/24543
