### ISSUE TITLE
Nice but edgy

### ISSUE THREAD

**Issue by twothe** [microsoft/BosqueLanguage#84]
I like the idea of reducing complexity of the programming language itself, however while Bosque is a great first step, there are many new complexities introduced by trying to be less complex:

**Semicolon**
Considering all modern languages, the ; can be considered deprecated.

**Function**
A function is a function and should only be named function. Naming it function, method, or fn depending on context is very confusing and error-prone.

Suggestion: 
Stick to fn in all cases. It is short and everyone with a mathematical background will recognize it.

**Confusing use of -> <- <~ => ::**
It is very confusing to see so many operators be used in so many variants and use-cases, while they all mean about the same. It would be a lot better if there would be only one functionality across the board. Additionally please keep in mind that keyboards in other languages might have troubles accessing the special characters you use.

Suggestion:
Use -> and <- exclusively (- is available easily on all keyboards). Have -> be the functional declaration and <- be the defer-from assignment (which is inherently a function), call functions on a class via . operator, don't use :: at all.
Examples:

    var doubleIt = (x: Int): Int -> x * 2
    fn tripleIt(a: Int): Int -> a * 3
    fn myComplexExample(v: {x: Int, y: Int}): {x: Int, y: Int} -> v<-( x = doubleIt(v.x) )

**Logical && ||**
In most cases while programming you are going to use the logical operators for comparison, yet the bit-wise operators are still the shorter version because of legacy reasons, making the code harder to read then it should be.

Suggestion:
User & and | for logical operations, && and || for bit-wise operations.

    if (a == 2 | a == 3 & flag == true)
    var bitset = (x && 0xFF) >> 2

**exists operator**
Seeing `x != none` notations all over the place could be simplified by an exist operator:

    if (x exists & x > 2) ...

**Multiple-checks in one operation**
One of the many pitfalls in programming is a complex/hard to read check of variables in the form of `x != none && x >= 2 && x < 10 && y != none && y >= 0 && x < y` It would be great if this could be written in a much simpler way.

Suggestion:
Allow multiple checks on a var at once:

    if ( y (exists & >= 0) & x (exists & >= 2 & < 10 & < y)  )
    fn within(x: Int, low: Int, high: Int): Bool -> x (>= low & <= high)

**Within syntax**
I noticed the `0 <= x` check in the example game code and can't help but to say that this is extremely confusing to read. In most languages the operand comes first, and it does so most of the time in Bosque as well, having it suddenly appear second is not helping readability.

Suggestion:
Drop this.

**if..elif..else**
If-else-chains are neither good for readability nor for performance and can safely be replaced by a switch/case statement.

Suggestion:
Simply drop the if/elif/else construct and use a case construct instead.

    fn estimateNumber(x: Int): String -> {
      case (x > 10) { return "Over ten" }  
      case (x (>= 7 & (%2 == 0)) { return "Big even" }
      else { return "Not quiet sure" }
    }

This would also allow for a short-hand assignment function like this:

    fn roleToDBId(role: String): Int -> 
      case "user": 1
      case "mod": 2
      case "admin": 999
      else: 0

Note the absence of a return, because : Is a short-hand notation for it. This is meant to erase fall-through issues. With this notation you would have to explicitly write something like 
`case x (== 0 | == 1): "first or second"`

**Comment by orcmid** [comment]
I am nervous about 

```
Logical && ||
In most cases while programming you are going to use the logical operators for comparison, yet the bit-wise operators are still the shorter version because of legacy reasons, making the code harder to read then it should be.
Suggestion:
User & and | for logical operations, && and || for bit-wise operations.
if (a == 2 | a == 3 & flag == true)
var bitset = (x && 0xFF) >> 2
```

1. For one, the use of & and | is considered both logical and bit-wise.  It is essentially imperative Boolean Algebra stuff.
2. Technically, in places I find them, && and || are conditionals, that have short-circuited evaluations.   I think the distinction is needed somehow (without thinking too hard whether Bosque is eager or lazy)..
3. How these relate with respect to operator-precedence is a consideration.

It may be wise to step back and look at these more carefully.

**Comment by twothe** [comment]
In computer languages the & is traditionally the bit-wise operator and && the logical operator. This was necessary in languages like C as things like `if (a && b)` and `if (a & b)` could both be equally valid statements, since 0 evaluates to false. While this is still practical such bit-wise equations have become extremely uncommon in modern languages, and even in C - unless you are programming hardware - it is not seen as often as it was during the 'old' days.

    var a = input | 0

That is one of the short-circuit evaluations that are still really common (and useful), but they are a direct result of how `and` and `or` are implemented. In languages like JavaScript `or` is implemented as

    a || b == a ? b : a

In other languages like Java they are implemented as a direct logical test, so the above statement would cause an error since input and 0 are no booleans.

**Comment by orcmid** [comment]
I think of SML as a precedent, except "and also" instead of && and "or else" instead of || are nice ways out of that problem about infix choices.  These should not be called logical, but conditional, although I agree that if you are strongly-typed, they must be on Boolean-yielding operands.

Concerning logical (i.e., any Boolean including bitwise vector) operations, think Bloom filters, hashing (not necessarily crypto), digest and encryption algorithms, working with character encodings, etc.   Then there are about 250 pp in Knuth ACP v.4A.

**Comment by wandyezj** [comment]
Regarding && and ||,

Changing the common meaning of && and & and || and | may be very confusing for programmers coming from the common languages used today and could lead to mistakes.

Python uses `and` and `or` which are much easier for people learning programming for the first time to understand than an explanation of the && and || key.

bitwise operations are useful in many contexts and I would be nervous about replacing the fairly standard & and | expressions with something else.

It would be convenient if all boolean expressions are short circuited and no ban functions with side effects from being used inside boolean expressions. Since side effects as part of boolean expressions are difficult to reason about in boolean expressions.

**Comment by wandyezj** [comment]
```
Function
A function is a function and should only be named function. Naming it function, method, or fn depending on context is very confusing and error-prone.
```

I agree with `A function is a function and should only be named function`.

I'm not sure abbreviating function to fn is worth it. For one it creates a barrier for new people learning the language since instead of the more obvious `function`  they now need to both learn the abbreviation for the common name and the concept.

I would point out that many people to do programming do not have a strong mathematics background. Requiring or assuming a strong mathematics seems to create an unnecessary barrier.

**Comment by norman784** [comment]
I must disagree, `fn` isn't a hard keyword to learn, write `function` takes longer and you can get quickly used to write just `fn`, even as a new programmer will be easy IMHO.

**Comment by wandyezj** [comment]
`fn isn't a hard keyword to learn`
- Nothing is hard to learn once you spend enough time learning it.
- Small barrier add up to big barriers.

`write function takes longer`
- See intellisense and autocomplete.
- If we are really concerned about typing then why not abbreviate to `f`?
- or why not skip the declaration entirely?
```
functionName(arguments)
{

}
```
