### ISSUE TITLE
VS Code Extension not  loading

### ISSUE THREAD

**Issue by kmasif** [microsoft/BosqueLanguage#88]
Copying the folder `bosque-language-tools/` into your VS Code extension folder is suppose to load the extension. But it is not showing up in the Extension list. I have tried with both VS Code and VS Code Insiders.

**Platform:** Windows x64
**VS Code:** 1.33.1
**VS Code Insiders:** 1.34.0-insider

**Comment by MairwunNx** [comment]
I use Visual Studio Code - Insiders and everything is fine with me. 
![image](https://user-images.githubusercontent.com/39625750/56506812-3bed1080-6528-11e9-90da-b667aba630af.png)

Maybe you not restart Visual Studio Code? Or put a folder in the wrong place?

**Comment by farleykr** [comment]
This may have to do with the fact that it's not an official extension and you're just copying a folder.  I've followed the instructions and copied the `bosque-language-tools/` folder to `~/.vscode/extensions`  on my system and the extension works even though it's not listed under my enabled extensions in VSCode.  Have you tried writing any Bosque code since copying the `bosque-language-tools/` folder to see if syntax highlighting or anything works?

**Comment by MairwunNx** [comment]
@farleykr +1. Also maybe he not true set extension to source file :D

**Comment by emosGambler** [comment]
If this is a correct highlighting then it works for me.

![image](https://user-images.githubusercontent.com/20873814/57177859-b858eb00-6e68-11e9-8801-0f27c174d56b.png)

**Comment by mrkmarron** [comment]
Seems like the issue is resolved.
