### ISSUE TITLE
Why there is no proper logo of the Programming Language?

### ISSUE THREAD

**Issue by Hritam-cse** [microsoft/BosqueLanguage#94]
Every programming language has its own logo. I think there should be a proper logo of the new **Bosque Programming Language**.

**Comment by cigetbudi** [comment]
why we don't just submitting together and choose the suitable one.

(sorry for bad english)

**Comment by jakalkhalili** [comment]
Yes, but Bosque is now in early development stage. We should think about it when it reach nearly production status.

**Comment by hearot** [comment]
> Yes, but Bosque is now in early development stage. We should think about it when it reach nearly production status.

I agree. There should be a logo, but that's not a priority.

**Comment by zeeshanshaikh001** [comment]
I think we can start submitting the logo suggestions to Microsoft.

**Comment by Hritam-cse** [comment]
> I think we can start submitting the logo suggestions to Microsoft.

But how can we suggest logo to Microsoft?

**Comment by mrkmarron** [comment]
I am terrible at graphics so happy for any help here. 

We can start with an unoffical logo from the community and, if we like it and want to make a real part of the branding, I'll work with the right folks in Microsoft as needed.

**Comment by NickStarlight** [comment]
If i may suggest, i would definitely go down the simple path, choosing a single letter as logo(As most languages do).
On the creator words, 'bosque' => it is the forest by a river, something could be done with a B on that, since we lack proper background to use as creative basis.
Also would use the Fluent/Metro Color Pallete, since, well, it's Microsoft.

**Comment by NickStarlight** [comment]
![Bosque_Logo](https://user-images.githubusercontent.com/5606763/56779377-1fafd480-67b1-11e9-9f5d-694c3640ae9e.png)

I would suggest something along those lines.
Since Bosque runs over NodeJS and TypeScript, both having an almost the same logo, why not keep the consistency?
The color green was choosen regarding forests(Bosque, duh), the mix of JavaScript and TypeScript logo colors (Blue + Yellow = Green) and NodeJS green color influence, respecting the Metro color scheme that Microsoft uses(#008a00 Emerald).
Font is the same as TS and JS logos(Neutra Text Bold).

Altought sounds kinda bad keeping the 'S' pattern, you now, sounds like BS.

As for an alternate logo just plain use the pattern that MSFT has been using for their recent products.
Segoe(I think?)-green-Bosque-Text-Over-White-Background.

**Comment by farleykr** [comment]
@NickStarlight +1.  I really like this one.

**Comment by NickStarlight** [comment]
@farleykr Would something alongs those lines suit?

![Bosque_Logo](https://user-images.githubusercontent.com/5606763/56871414-fd59c900-69f3-11e9-9cd0-6b39cd0e60d7.png)
![Bosque_Logo_Plain](https://user-images.githubusercontent.com/5606763/56871415-ffbc2300-69f3-11e9-8748-4bf4d6c42c69.png)

**Comment by Hritam-cse** [comment]
> @farleykr Would something alongs those lines suit?

Great!

**Comment by farleykr** [comment]
@NickStarlight,

I think it looks pretty cool.  I'm sure if/when @mrkmarron takes it to the folks in Microsoft they'll be able to provide suggestions or make modifications as needed.

**Comment by hearot** [comment]
Awesome!

**Comment by mrkmarron** [comment]
I don't think we have any major feedback. If @NickStarlight wants to open a PR to include these assets (maybe in a new directory called resources at the top-level in the repo) we can have them for use as community logos.

**Comment by NickStarlight** [comment]
@mrkmarron I will prepare the required files and do it soon as I can, thank you for the feedback.

**Comment by NickStarlight** [comment]
After looking thought the current design iteration that Microsoft is using(Fluent/Fabric) i came with:

![Fabric_Bosque_Logo](https://user-images.githubusercontent.com/5606763/59577316-983c5e80-9099-11e9-923d-f9e753f76fbd.png)

![Bosque_Typography](https://user-images.githubusercontent.com/5606763/59577324-9ffc0300-9099-11e9-8b9c-c30a625aeed1.png)

The icon itself is heavily inspired on the new Office logos, since they are the only public reference of branding I could find that uses the Fluent/Fabric design.
I didn't use B as primary brand letter because of Bing and another products like Power BI that could cause some confusion, instead, I used Lambda, since anonymous functions are ubiquitous in functional programming, and Bosque is a functional programming language.


The shade of green is a little different but does respect the color scheme proposed.
It is, unfortunately, very similar to the Office branding pattern, specially Excell, altought I don't think that could be an issue.

**Comment by Hritam-cse** [comment]
The logo is looking Great!

**Comment by mrkmarron** [comment]
Should be resolved with commit #183
